### PR TITLE
Added some additional terms from MSCD

### PR DESCRIPTION
**Pull request by danrubins**
Kyle, you and Ansel have been doing some really interesting work with CommonForm. Here are some additional contributions we've found while working with MSCD.

### CODE REVIEW

**Comment by kemitchell** [comment]
You may like to know about:
1. https://github.com/commonform/commonform-mscd
2. https://github.com/kemitchell/mscd.json

**Comment by danrubins** [comment]
Oh, nice - mscd.json looks more nuanced for some of these items. Not all of the changes in this PR make sense as 1:1 replacements and I already see a couple of them included in mscd.json.

**Comment by kemitchell** [comment]
I think "shall never" and "shall in no way" are appropriate additions to wordy-words. I will cherry-pick and tweak commit messages shortly.

I've landed a couple others in mscd.json@0.1.4.

**Comment by kemitchell** [comment]
Cherry picks landed in 0.0.14. Please feel free to reopen if you think I missed something.

Many thanks for this PR!

**Pull request closed without merging**
